server:
  port: 8201

spring:
  application:
    name: nacos-provider
  config:
    import:
      - optional:nacos:nacos-provider.yaml
      - optional:nacos:application-common.yaml
      - optional:nacos:service-config.json?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'